status:
  port: "16241"
  host: null

storages:
  - name: main
    plugin: fs
    config:
      directory: /var/lib/yandex/unified_agent/main
      max_partition_size: 100mb
      max_segment_size: 10mb

channels:
  - name: cloud_monitoring
    channel:
      pipe:
        - storage_ref:
            name: main
      output:
        plugin: yc_metrics
        config:
          folder_id: "b1guohhtr6sb4o7qtgdi"
          iam:
            cloud_meta: {}

routes:
  - input:
      plugin: agent_metrics
      config:
        namespace: ua
    channel:
      pipe:
        - filter:
            plugin: filter_metrics
            config:
              match: "{scope=health}"
      channel_ref:
        name: cloud_monitoring

  - input:
      plugin: linux_metrics
      config:
        proc_directory: "/ua_proc"
        namespace: sys
    channel:
      channel_ref:
        name: cloud_monitoring
          
  - input:
      plugin: metrics_pull
      config:
        url: http://bot:9100/metrics
        format:
          prometheus: { }
        namespace: app
    channel:
      channel_ref:
        name: cloud_monitoring

import:
  - /etc/yandex/unified_agent/conf.d/*.yml
