from __future__ import annotations
import typing, abc, enum
from stubhelper import *

import System


class AssemblyHashAlgorithm(enum.Enum, System.IComparable, System.IFormattable, System.IConvertible, System.Enum):
    None_: int = ...
    MD5: int = ...
    SHA1: int = ...
    SHA256: int = ...
    SHA384: int = ...
    SHA512: int = ...

class AssemblyVersionCompatibility(enum.Enum, System.IComparable, System.IFormattable, System.IConvertible, System.Enum):
    SameMachine: int = ...
    SameProcess: int = ...
    SameDomain: int = ...

