from __future__ import annotations
import typing, abc, enum
from stubhelper import *

import System


class Error(enum.Enum, System.IComparable, System.IFormattable, System.IConvertible, System.Enum):
    EPERM: int = ...
    ENOENT: int = ...
    ESRCH: int = ...
    EINTR: int = ...
    ECHILD: int = ...
    EAGAIN: int = ...
    EACCES: int = ...
    EEXIST: int = ...
    ENOTDIR: int = ...
    EISDIR: int = ...
    EPIPE: int = ...
    ECONNABORTED: int = ...
    ECONNRESET: int = ...
    ESHUTDOWN: int = ...
    ETIMEDOUT: int = ...
    ECONNREFUSED: int = ...
    EALREADY: int = ...
    EINPROGRESS: int = ...
    WSAEWOULDBLOCK: int = ...
    WSAEINPROGRESS: int = ...
    WSAEALREADY: int = ...
    WSAECONNABORTED: int = ...
    WSAECONNRESET: int = ...
    WSAESHUTDOWN: int = ...
    WSAETIMEDOUT: int = ...
    WSAECONNREFUSED: int = ...

