from __future__ import annotations
import typing, abc, enum
from stubhelper import *

import System


class PropertyIndex(System.Object, abc.ABC):
    @typing.overload
    def __init__(self, **kwargs):
        ...

    # static fields
    Name: int = ...
    General_Category: int = ...
    Canonical_Combining_Class: int = ...
    Bidi_Class: int = ...
    Decomposition_Type: int = ...
    Numeric_Value_Decimal: int = ...
    Numeric_Value_Digit: int = ...
    Numeric_Value_Numeric: int = ...
    Bidi_Mirrored: int = ...
    East_Asian_Width: int = ...

    # properties
    # methods
