from __future__ import annotations
import typing, abc, enum
from stubhelper import *

import System


class Token(enum.Enum, System.IComparable, System.IFormattable, System.IConvertible, System.Enum):
    PI: int = ...
    Doctype: int = ...
    Comment: int = ...
    CData: int = ...
    StartElement: int = ...
    EndElement: int = ...
    LongEndElement: int = ...
    StartAttribute: int = ...
    EndAttribute: int = ...
    Content: int = ...
    Base64: int = ...
    RawData: int = ...
    Whitespace: int = ...
    Empty: int = ...

