from __future__ import annotations
import typing, abc, enum
from stubhelper import *

import System


class LineEnding(enum.Enum, System.IComparable, System.IFormattable, System.IConvertible, System.Enum):
    None_: int = ...
    CR: int = ...
    LF: int = ...
    CRLF: int = ...
    All: int = ...

