from __future__ import annotations
import typing, abc, enum
from stubhelper import *

import System


class TryGetFuncActionArgsResult(enum.Enum, System.IComparable, System.IFormattable, System.IConvertible, System.Enum):
    Valid: int = ...
    ArgumentNull: int = ...
    ByRef: int = ...
    PointerOrVoid: int = ...

