name: deploy

on: workflow_dispatch

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          cr.yandex/crprntimcbd0ve7l3aph/adventure-bot
        tags: |
          type=sha
          type=raw,value=latest
          type=raw,value=r${{ github.run_number }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Yandex Container Registry
      uses: docker/login-action@v2
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YANDEX_KEY_JSON }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

